### PR TITLE
Powerful & lightweight WebSocket wrapper/library 

### PR DESCRIPTION
**Pull request by HRDepartment**
Everything still works. Just much cleaner!

Note that I wrote this myself, there's nothing in README.md on purpose.

### CODE REVIEW

**Comment by coyotte508** [comment]
This pull request cannot be automatically merged. 

When pulling my commits, do it this way:

git fetch coyotte
git merge coyotte/master

(where you did git remote add coyotte <github repo> before)

That way the commits won't duplicate

**Comment by HRDepartment** [comment]
GitHub for Windows likes messing things like that up. I'll make a new pull with this fixed.

**Comment by coyotte508** [comment]
That's not the only problem, I'm sorry but to me this just looks like useless code in the current context, so it won't be put in. That was a nice thought though.

**Comment by HRDepartment** [comment]
In that case, I'll just let it go.

**Pull request closed without merging**
